# Generated by Django 3.2.3 on 2021-05-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='background_color',
            field=models.CharField(choices=[('yellow', 'yellow'), ('gray', 'gray'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('purple', 'purple'), ('indigo', 'indigo')], default='yellow', max_length=10),
        ),
    ]
